version: '3.4'

services:

  librarydb:
    container_name: librarydb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SwN12345678
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_library:/var/opt/mssql

  library.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__librarydb=Server=librarydb;Database=librarydb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
      - ConnectionStrings__hangfiredb=Server=librarydb;Database=hangfiredb;User Id=sa;Password=SwN12345678;Encrypt=False;TrustServerCertificate=True
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - librarydb
